---
title: "Psicometria aplicada no R - Aula 4 (5 de maio de 2021)"
output:
  html_notebook:
    toc: yes
    toc_float: yes
    number_sections: yes
    theme: united
    highlight: textmate
editor_options: 
  chunk_output_type: inline
---

# Aula 4 - Medidas clínicas

## pacotes

```{r}
pacman::p_load(tidyverse, summarytools, arsenal, knitr)
```


## Pegar os dados


```{r}
ds_full <- read.csv(url("https://osf.io/hzx8v/download"))
```

## Pequeno ajuste 

```{r}
ds_full$age_group %>% table()
ds_full <- ds_full %>% 
  mutate(age_group = factor(age_group, levels = c("[5,6]", "(6,8]", "(8,10]" , "(10,12]", 
                                                  "(12,14]", "(14,16]", "(16,18]")))
```


## Verificar distribuição das respostas

```{r, eval = FALSE }
view(dfSummary(ds_full)) 
```

## Características da amostra

```{r}
ds_full %>% 
  select(sex, age_group, group) %>% 
  tableby(group ~ ., data = . ) %>% 
  summary() %>% 
  kable(.)
  
```
```{r}
ds_full %>% 
  filter(group == "typical") %>% 
  select(sex, age_group,) %>% 
  tableby(~ ., data = . ) %>% 
  summary() %>% 
  kable("html", escape = F)
  
```

## Distribuição dos resultados

```{r}
ds_full %>% 
  filter(group == "typical") %>% 
  ggplot(., aes(total)) +
   geom_histogram(breaks = seq(0, 40, by = 5),
                  aes(x=total,y=..density..), 
                  position="identity", alpha = 0.5) + 
  geom_density(alpha=0.2, fill = "blue") +
  theme_bw()
```





> Fim da aula 3